/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module controller(clk, reset, req_valid, req_write, req_addr, req_wdata, req_ready, rsp_valid, rsp_error, rsp_rdata, mem_commit, mem_write, mem_addr, mem_wdata, mem_rdata, mem_fault);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  reg [3:0] addr_latched;
  reg busy;
  input clk;
  wire clk;
  reg [7:0] data_latched;
  output [3:0] mem_addr;
  wire [3:0] mem_addr;
  output mem_commit;
  wire mem_commit;
  input mem_fault;
  wire mem_fault;
  input [7:0] mem_rdata;
  wire [7:0] mem_rdata;
  output [7:0] mem_wdata;
  wire [7:0] mem_wdata;
  output mem_write;
  wire mem_write;
  reg [7:0] remaining;
  input [3:0] req_addr;
  wire [3:0] req_addr;
  output req_ready;
  wire req_ready;
  input req_valid;
  wire req_valid;
  input [7:0] req_wdata;
  wire [7:0] req_wdata;
  input req_write;
  wire req_write;
  input reset;
  wire reset;
  output rsp_error;
  reg rsp_error;
  output [7:0] rsp_rdata;
  reg [7:0] rsp_rdata;
  output rsp_valid;
  reg rsp_valid;
  reg write_latched;
  assign req_ready = ~(reset | busy);
  assign _004_ = req_ready & req_valid;
  assign _000_ = _004_ | busy;
  assign _002_ = reset | ~(busy);
  assign _008_ = remaining[1] | ~(remaining[0]);
  assign _009_ = ~(remaining[3] | remaining[2]);
  assign _010_ = _009_ & ~(_008_);
  assign _011_ = ~(remaining[5] | remaining[4]);
  assign _012_ = remaining[7] | remaining[6];
  assign _013_ = _012_ | ~(_011_);
  assign _003_ = _010_ & ~(_013_);
  assign _014_ = ~_004_;
  assign _015_ = ~(_003_ & busy);
  assign _001_ = _014_ & ~(_015_);
  assign mem_commit = ~(_015_ | reset);
  assign _046_ = mem_rdata[0] & ~(mem_fault);
  assign _047_ = mem_rdata[1] & ~(mem_fault);
  assign _048_ = mem_rdata[2] & ~(mem_fault);
  assign _049_ = mem_rdata[3] & ~(mem_fault);
  assign _050_ = mem_rdata[4] & ~(mem_fault);
  assign _051_ = mem_rdata[5] & ~(mem_fault);
  assign _052_ = mem_rdata[6] & ~(mem_fault);
  assign _053_ = mem_rdata[7] & ~(mem_fault);
  assign _016_ = _003_ | remaining[0];
  assign _037_ = _014_ & ~(_016_);
  assign _017_ = ~req_write;
  assign _018_ = ~(remaining[1] ^ remaining[0]);
  assign _038_ = _004_ ? _017_ : _018_;
  assign _019_ = ~(remaining[1] | remaining[0]);
  assign _020_ = ~(_019_ ^ remaining[2]);
  assign _021_ = ~(_020_ | _003_);
  assign _039_ = _004_ ? req_write : _021_;
  assign _022_ = _019_ & ~(remaining[2]);
  assign _023_ = ~(_022_ ^ remaining[3]);
  assign _024_ = _023_ | _003_;
  assign _040_ = _014_ & ~(_024_);
  assign _025_ = _009_ & ~(_019_);
  assign _026_ = _009_ & ~(_025_);
  assign _027_ = ~(_026_ ^ remaining[4]);
  assign _028_ = _027_ | _003_;
  assign _041_ = _014_ & ~(_028_);
  assign _029_ = _026_ & ~(remaining[4]);
  assign _030_ = ~(_029_ ^ remaining[5]);
  assign _031_ = _030_ | _003_;
  assign _042_ = _014_ & ~(_031_);
  assign _032_ = _011_ & ~(_026_);
  assign _033_ = _032_ | ~(_011_);
  assign _034_ = _033_ ^ remaining[6];
  assign _035_ = _034_ | _003_;
  assign _043_ = _014_ & ~(_035_);
  assign _036_ = _033_ | remaining[6];
  assign _005_ = _036_ ^ remaining[7];
  assign _006_ = _005_ | _003_;
  assign _044_ = _014_ & ~(_006_);
  assign _007_ = busy & ~(_003_);
  assign _045_ = _007_ | ~(_014_);
  always @(posedge clk)
    if (reset) busy <= 1'h0;
    else busy <= _045_;
  always @(posedge clk)
    if (reset) rsp_error <= 1'h0;
    else if (_001_) rsp_error <= mem_fault;
  always @(posedge clk)
    if (reset) rsp_rdata[0] <= 1'h0;
    else if (_001_) rsp_rdata[0] <= _046_;
  always @(posedge clk)
    if (reset) rsp_rdata[1] <= 1'h0;
    else if (_001_) rsp_rdata[1] <= _047_;
  always @(posedge clk)
    if (reset) rsp_rdata[2] <= 1'h0;
    else if (_001_) rsp_rdata[2] <= _048_;
  always @(posedge clk)
    if (reset) rsp_rdata[3] <= 1'h0;
    else if (_001_) rsp_rdata[3] <= _049_;
  always @(posedge clk)
    if (reset) rsp_rdata[4] <= 1'h0;
    else if (_001_) rsp_rdata[4] <= _050_;
  always @(posedge clk)
    if (reset) rsp_rdata[5] <= 1'h0;
    else if (_001_) rsp_rdata[5] <= _051_;
  always @(posedge clk)
    if (reset) rsp_rdata[6] <= 1'h0;
    else if (_001_) rsp_rdata[6] <= _052_;
  always @(posedge clk)
    if (reset) rsp_rdata[7] <= 1'h0;
    else if (_001_) rsp_rdata[7] <= _053_;
  always @(posedge clk)
    if (_002_) rsp_valid <= 1'h0;
    else rsp_valid <= _003_;
  always @(posedge clk)
    if (reset) write_latched <= 1'h0;
    else if (_004_) write_latched <= req_write;
  always @(posedge clk)
    if (reset) addr_latched[0] <= 1'h0;
    else if (_004_) addr_latched[0] <= req_addr[0];
  always @(posedge clk)
    if (reset) addr_latched[1] <= 1'h0;
    else if (_004_) addr_latched[1] <= req_addr[1];
  always @(posedge clk)
    if (reset) addr_latched[2] <= 1'h0;
    else if (_004_) addr_latched[2] <= req_addr[2];
  always @(posedge clk)
    if (reset) addr_latched[3] <= 1'h0;
    else if (_004_) addr_latched[3] <= req_addr[3];
  always @(posedge clk)
    if (reset) data_latched[0] <= 1'h0;
    else if (_004_) data_latched[0] <= req_wdata[0];
  always @(posedge clk)
    if (reset) data_latched[1] <= 1'h0;
    else if (_004_) data_latched[1] <= req_wdata[1];
  always @(posedge clk)
    if (reset) data_latched[2] <= 1'h0;
    else if (_004_) data_latched[2] <= req_wdata[2];
  always @(posedge clk)
    if (reset) data_latched[3] <= 1'h0;
    else if (_004_) data_latched[3] <= req_wdata[3];
  always @(posedge clk)
    if (reset) data_latched[4] <= 1'h0;
    else if (_004_) data_latched[4] <= req_wdata[4];
  always @(posedge clk)
    if (reset) data_latched[5] <= 1'h0;
    else if (_004_) data_latched[5] <= req_wdata[5];
  always @(posedge clk)
    if (reset) data_latched[6] <= 1'h0;
    else if (_004_) data_latched[6] <= req_wdata[6];
  always @(posedge clk)
    if (reset) data_latched[7] <= 1'h0;
    else if (_004_) data_latched[7] <= req_wdata[7];
  always @(posedge clk)
    if (reset) remaining[0] <= 1'h0;
    else if (_000_) remaining[0] <= _037_;
  always @(posedge clk)
    if (reset) remaining[1] <= 1'h0;
    else if (_000_) remaining[1] <= _038_;
  always @(posedge clk)
    if (reset) remaining[2] <= 1'h0;
    else if (_000_) remaining[2] <= _039_;
  always @(posedge clk)
    if (reset) remaining[3] <= 1'h0;
    else if (_000_) remaining[3] <= _040_;
  always @(posedge clk)
    if (reset) remaining[4] <= 1'h0;
    else if (_000_) remaining[4] <= _041_;
  always @(posedge clk)
    if (reset) remaining[5] <= 1'h0;
    else if (_000_) remaining[5] <= _042_;
  always @(posedge clk)
    if (reset) remaining[6] <= 1'h0;
    else if (_000_) remaining[6] <= _043_;
  always @(posedge clk)
    if (reset) remaining[7] <= 1'h0;
    else if (_000_) remaining[7] <= _044_;
  assign mem_addr = addr_latched;
  assign mem_wdata = data_latched;
  assign mem_write = write_latched;
endmodule
